---
- name: Configure Elasticsearch
  become: true
  template:
    src: elasticsearch.yml.j2
    mode: 0644
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart Elasticsearch

- name: Create a directory for Java options
  become: true
  file:
    path: /etc/elasticsearch/jvm.options.d
    state: directory
    mode: 0755

- name: Java memory limits
  become: true
  copy:
    dest: /etc/elasticsearch/jvm.options.d/local.options
    content: |
      -Xms{{ es_java_memory_gb }}g
      -Xmx{{ es_java_memory_gb }}g
    mode: 0644
  notify: restart Elasticsearch
