---
- name: Install Elasticsearch
  become: true
  yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
    disable_gpg_check: true
  notify: restart Elasticsearch
