---
- name: Install Kibana rpm
  become: true
  yum:
    name: "/tmp/{{ pkg_name }}"
    state: present
    disable_gpg_check: true
  notify: restart Kibana
  when: pkg_mgr == 'yum'

- name: Install Kibana deb
  become: true
  apt:
    deb: "/tmp/{{ pkg_name }}"
    state: present
  notify: restart Kibana
  when: pkg_mgr == 'apt'
