---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/jrei/systemd-centos:8
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro,z"
    command: /sbin/init

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        elk_stack_version: "7.14.1"
        elasticsearch_version: "{{ elk_stack_version }}"
        es_java_memory_gb: 1

verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
